
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hasmot Ali Hasu
 */
public class addAdmin extends javax.swing.JFrame {

    /**
     * Creates new form addAdmin
     */
    
    
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs= null;
    
    
    public addAdmin() {
        super(" Add Admin");
        initComponents();
        conn = databaseConnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        adminSubmitBTN = new javax.swing.JButton();
        adminBackBTN = new javax.swing.JButton();
        adminName = new javax.swing.JTextField();
        adminEmail = new javax.swing.JTextField();
        adminPassword = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        homeBTNunderFile = new javax.swing.JMenuItem();
        logoutMenuUnderFile = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenu();
        aboutBTN = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jLabel1.setText("Name:");

        jLabel2.setText("Email:");

        jLabel3.setText("Password:");

        adminSubmitBTN.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hasmot Ali Hasu\\Documents\\NetBeansProjects\\Student Registration\\student\\project Image\\submit.png")); // NOI18N
        adminSubmitBTN.setText("Submit");
        adminSubmitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminSubmitBTNActionPerformed(evt);
            }
        });

        adminBackBTN.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hasmot Ali Hasu\\Documents\\NetBeansProjects\\Student Registration\\student\\project Image\\back.png")); // NOI18N
        adminBackBTN.setText("Back");
        adminBackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBackBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(adminSubmitBTN)
                        .addGap(33, 33, 33)
                        .addComponent(adminBackBTN))
                    .addComponent(adminName)
                    .addComponent(adminEmail)
                    .addComponent(adminPassword))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(adminName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminSubmitBTN)
                    .addComponent(adminBackBTN))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        fileMenu.setText("File");

        homeBTNunderFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        homeBTNunderFile.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hasmot Ali Hasu\\Documents\\NetBeansProjects\\Student Registration\\student\\project Image\\home.png")); // NOI18N
        homeBTNunderFile.setText("Home");
        homeBTNunderFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBTNunderFileActionPerformed(evt);
            }
        });
        fileMenu.add(homeBTNunderFile);

        logoutMenuUnderFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        logoutMenuUnderFile.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hasmot Ali Hasu\\Documents\\NetBeansProjects\\Student Registration\\student\\project Image\\logout.png")); // NOI18N
        logoutMenuUnderFile.setText("Logout");
        logoutMenuUnderFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuUnderFileActionPerformed(evt);
            }
        });
        fileMenu.add(logoutMenuUnderFile);

        jMenuBar1.add(fileMenu);

        aboutMenu.setText("About");

        aboutBTN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        aboutBTN.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hasmot Ali Hasu\\Documents\\NetBeansProjects\\Student Registration\\student\\project Image\\about.png")); // NOI18N
        aboutBTN.setText("About");
        aboutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBTNActionPerformed(evt);
            }
        });
        aboutMenu.add(aboutBTN);

        jMenuBar1.add(aboutMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(416, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeBTNunderFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBTNunderFileActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        home Object = new home();
        Object.setVisible(true);
    }//GEN-LAST:event_homeBTNunderFileActionPerformed

    private void logoutMenuUnderFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuUnderFileActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        logIn Object = new logIn();
        Object.setVisible(true);
    }//GEN-LAST:event_logoutMenuUnderFileActionPerformed

    private void aboutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBTNActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        About Object = new About();
        Object.setVisible(true);
    }//GEN-LAST:event_aboutBTNActionPerformed

    private void adminBackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBackBTNActionPerformed
        // TODO add your handling code here:
        
        setVisible(false);
        home Object = new home();
        Object.setVisible(true);
    }//GEN-LAST:event_adminBackBTNActionPerformed

    private void adminSubmitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminSubmitBTNActionPerformed
        // TODO add your handling code here:
        
       try{
           
           stmt = conn.createStatement();
           
           String adName = adminName.getText();
           String adMail = adminEmail.getText();
           String adPass = adminPassword.getText();
           
           String sql = "INSERT INTO admin(name, mail, password) VALUES('"+adName+"','"+adMail+"','"+adPass+"')";
           
           stmt.executeUpdate(sql);
           JOptionPane.showMessageDialog(null, "Admin Added!");
           
       }catch(SQLException e){
           JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_adminSubmitBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new addAdmin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutBTN;
    private javax.swing.JMenu aboutMenu;
    private javax.swing.JButton adminBackBTN;
    private javax.swing.JTextField adminEmail;
    private javax.swing.JTextField adminName;
    private javax.swing.JPasswordField adminPassword;
    private javax.swing.JButton adminSubmitBTN;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem homeBTNunderFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem logoutMenuUnderFile;
    // End of variables declaration//GEN-END:variables
}
