/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hasmot Ali Hasu
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addStudentBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        studentOperationBTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        showStudentBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        showAdminBTN = new javax.swing.JButton();
        adminOperationBTN = new javax.swing.JButton();
        addAdminBTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        homeBTNunderFile = new javax.swing.JMenuItem();
        logoutMenuUnderFile = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenu();
        aboutBTN = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon("logo.png")); // NOI18N

        addStudentBTN.setIcon(new javax.swing.ImageIcon("AddStudent.png")); // NOI18N
        addStudentBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentBTNActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add Student");

        studentOperationBTN.setIcon(new javax.swing.ImageIcon("configuration.png")); // NOI18N
        studentOperationBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentOperationBTNActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Operation");

        showStudentBTN.setIcon(new javax.swing.ImageIcon("showStudent.png")); // NOI18N
        showStudentBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showStudentBTNActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Show Student");

        showAdminBTN.setIcon(new javax.swing.ImageIcon("showAdmin.png")); // NOI18N
        showAdminBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAdminBTNActionPerformed(evt);
            }
        });

        adminOperationBTN.setIcon(new javax.swing.ImageIcon("configuration1.png")); // NOI18N
        adminOperationBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminOperationBTNActionPerformed(evt);
            }
        });

        addAdminBTN.setIcon(new javax.swing.ImageIcon("addAdmin.png")); // NOI18N
        addAdminBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdminBTNActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Add Admin");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Operation");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Show Admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(76, 76, 76)
                .addComponent(jLabel4)
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(42, 42, 42)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6)
                                    .addGap(84, 84, 84)
                                    .addComponent(jLabel7)
                                    .addGap(26, 26, 26))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(addAdminBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(adminOperationBTN)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(showAdminBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addStudentBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentOperationBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showStudentBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showStudentBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(studentOperationBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(addStudentBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showAdminBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(adminOperationBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(addAdminBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6))
                    .addComponent(jLabel5))
                .addGap(28, 28, 28))
        );

        fileMenu.setText("File");

        homeBTNunderFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        homeBTNunderFile.setIcon(new javax.swing.ImageIcon("home.png")); // NOI18N
        homeBTNunderFile.setText("Home");
        homeBTNunderFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBTNunderFileActionPerformed(evt);
            }
        });
        fileMenu.add(homeBTNunderFile);

        logoutMenuUnderFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        logoutMenuUnderFile.setIcon(new javax.swing.ImageIcon("logout.png")); // NOI18N
        logoutMenuUnderFile.setText("Logout");
        logoutMenuUnderFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuUnderFileActionPerformed(evt);
            }
        });
        fileMenu.add(logoutMenuUnderFile);

        jMenuBar1.add(fileMenu);

        aboutMenu.setText("About");

        aboutBTN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        aboutBTN.setIcon(new javax.swing.ImageIcon("about.png")); // NOI18N
        aboutBTN.setText("About");
        aboutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBTNActionPerformed(evt);
            }
        });
        aboutMenu.add(aboutBTN);

        jMenuBar1.add(aboutMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(530, 609));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addStudentBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentBTNActionPerformed
        // TODO add your handling code here:
                setVisible(false);
                AddStudent Object = new AddStudent();
                Object.setVisible(true);
    }//GEN-LAST:event_addStudentBTNActionPerformed

    private void aboutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBTNActionPerformed
        // TODO add your handling code here:
                setVisible(false);
                About Object = new About();
                Object.setVisible(true);
    }//GEN-LAST:event_aboutBTNActionPerformed

    private void logoutMenuUnderFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuUnderFileActionPerformed
        // TODO add your handling code here:
                setVisible(false);
                logIn Object = new logIn();
                Object.setVisible(true);
    }//GEN-LAST:event_logoutMenuUnderFileActionPerformed

    private void homeBTNunderFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBTNunderFileActionPerformed
        // TODO add your handling code here:
                setVisible(false);
                home Object = new home();
                Object.setVisible(true);
    }//GEN-LAST:event_homeBTNunderFileActionPerformed

    private void showStudentBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStudentBTNActionPerformed
        // TODO add your handling code here:
        
                setVisible(false);
                showStudent Object = new showStudent();
                Object.setVisible(true);
    }//GEN-LAST:event_showStudentBTNActionPerformed

    private void studentOperationBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentOperationBTNActionPerformed
        // TODO add your handling code here:
        
                setVisible(false);
                studentUpdate Object = new studentUpdate();
                Object.setVisible(true);
    }//GEN-LAST:event_studentOperationBTNActionPerformed

    private void addAdminBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdminBTNActionPerformed
        // TODO add your handling code here:
        
        setVisible(false);
        addAdmin Object = new addAdmin();
        Object.setVisible(true);
    }//GEN-LAST:event_addAdminBTNActionPerformed

    private void showAdminBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAdminBTNActionPerformed
        // TODO add your handling code here:
        
                setVisible(false);
                showAdmin Object = new showAdmin();
                Object.setVisible(true);
    }//GEN-LAST:event_showAdminBTNActionPerformed

    private void adminOperationBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminOperationBTNActionPerformed
        // TODO add your handling code here:
        
               setVisible(false);
                adminUpdate Object = new adminUpdate();
                Object.setVisible(true);
    }//GEN-LAST:event_adminOperationBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutBTN;
    private javax.swing.JMenu aboutMenu;
    private javax.swing.JButton addAdminBTN;
    private javax.swing.JButton addStudentBTN;
    private javax.swing.JButton adminOperationBTN;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem homeBTNunderFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem logoutMenuUnderFile;
    private javax.swing.JButton showAdminBTN;
    private javax.swing.JButton showStudentBTN;
    private javax.swing.JButton studentOperationBTN;
    // End of variables declaration//GEN-END:variables
}
