
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hasmot Ali Hasu
 */
public class studentUpdate extends javax.swing.JFrame {

    /**
     * Creates new form studentUpdate
     */
    
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs= null;
    public studentUpdate() {
        
        super("Student Update");
        initComponents();
        conn = databaseConnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        studentName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fatherName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cityName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        phoneNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        stdClass = new javax.swing.JTextField();
        addStudentSubmitBTN = new javax.swing.JButton();
        addStudentBackBTN = new javax.swing.JButton();
        deleteBTNunderSTDUpdate = new javax.swing.JButton();
        searchBTN = new javax.swing.JButton();
        stdID = new javax.swing.JLabel();
        studentID = new javax.swing.JTextField();
        blood = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        homeBTNunderFile = new javax.swing.JMenuItem();
        logoutMenuUnderFile = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenu();
        aboutBTN = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Father Name: ");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("City: ");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Blood: ");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone No: ");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Class: ");

        addStudentSubmitBTN.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hasmot Ali Hasu\\Documents\\NetBeansProjects\\Student Registration\\student\\project Image\\submit.png")); // NOI18N
        addStudentSubmitBTN.setText("Update");
        addStudentSubmitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentSubmitBTNActionPerformed(evt);
            }
        });

        addStudentBackBTN.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hasmot Ali Hasu\\Documents\\NetBeansProjects\\Student Registration\\student\\project Image\\back.png")); // NOI18N
        addStudentBackBTN.setText("Back");
        addStudentBackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentBackBTNActionPerformed(evt);
            }
        });

        deleteBTNunderSTDUpdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hasmot Ali Hasu\\Documents\\NetBeansProjects\\Student Registration\\student\\project Image\\cancel1.png")); // NOI18N
        deleteBTNunderSTDUpdate.setText("Delete");
        deleteBTNunderSTDUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNunderSTDUpdateActionPerformed(evt);
            }
        });

        searchBTN.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hasmot Ali Hasu\\Documents\\NetBeansProjects\\Student Registration\\student\\project Image\\loupe.png")); // NOI18N
        searchBTN.setText("Search");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        stdID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        stdID.setForeground(new java.awt.Color(255, 255, 255));
        stdID.setText("ID:");

        studentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDActionPerformed(evt);
            }
        });

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        fileMenu.setText("File");

        homeBTNunderFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        homeBTNunderFile.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hasmot Ali Hasu\\Documents\\NetBeansProjects\\Student Registration\\student\\project Image\\home.png")); // NOI18N
        homeBTNunderFile.setText("Home");
        homeBTNunderFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBTNunderFileActionPerformed(evt);
            }
        });
        fileMenu.add(homeBTNunderFile);

        logoutMenuUnderFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        logoutMenuUnderFile.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hasmot Ali Hasu\\Documents\\NetBeansProjects\\Student Registration\\student\\project Image\\logout.png")); // NOI18N
        logoutMenuUnderFile.setText("Logout");
        logoutMenuUnderFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuUnderFileActionPerformed(evt);
            }
        });
        fileMenu.add(logoutMenuUnderFile);

        jMenuBar1.add(fileMenu);

        aboutMenu.setText("About");

        aboutBTN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        aboutBTN.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hasmot Ali Hasu\\Documents\\NetBeansProjects\\Student Registration\\student\\project Image\\about.png")); // NOI18N
        aboutBTN.setText("About");
        aboutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBTNActionPerformed(evt);
            }
        });
        aboutMenu.add(aboutBTN);

        jMenuBar1.add(aboutMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(63, 63, 63)))
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(stdID))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(studentName)
                            .addComponent(fatherName)
                            .addComponent(cityName)
                            .addComponent(phoneNo)
                            .addComponent(stdClass, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(studentID)
                            .addComponent(blood))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(addStudentSubmitBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBTNunderSTDUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addStudentBackBTN)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdID)
                    .addComponent(studentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(blood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStudentSubmitBTN)
                    .addComponent(addStudentBackBTN)
                    .addComponent(deleteBTNunderSTDUpdate))
                .addGap(26, 26, 26))
        );

        setSize(new java.awt.Dimension(527, 544));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeBTNunderFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBTNunderFileActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        home Object = new home();
        Object.setVisible(true);
    }//GEN-LAST:event_homeBTNunderFileActionPerformed

    private void logoutMenuUnderFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuUnderFileActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        logIn Object = new logIn();
        Object.setVisible(true);
    }//GEN-LAST:event_logoutMenuUnderFileActionPerformed

    private void aboutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBTNActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        About Object = new About();
        Object.setVisible(true);
    }//GEN-LAST:event_aboutBTNActionPerformed

    private void addStudentSubmitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentSubmitBTNActionPerformed
        // TODO add your handling code here:
        try{
            stmt = conn.createStatement();
            int stdId = Integer.parseInt(studentID.getText());
            String stdname = studentName.getText();
            String stdfather = fatherName.getText();
            String stdcity = cityName.getText();
            String stdPhone = phoneNo.getText();
            int stdclass = Integer.parseInt(stdClass.getText());
            String stdblood = (String)blood.getText();

            String sql = "UPDATE student SET stdName = '"+stdname+"', stdFatherName = '"+stdfather+"', stdBloodGroup = '"+stdblood+"', stdCity = '"+stdcity+"', stdPhone = '"+stdPhone+"', stdClass = '"+stdclass+"' WHERE id = '"+stdId+"'";
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data Is Successfully Updated!");

        }catch(NumberFormatException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_addStudentSubmitBTNActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        // TODO add your handling code here:
        
        try{
            stmt = conn.createStatement();
            int stdid = Integer.parseInt(studentID.getText());
            String sql = "SELECT * FROM STUDENT WHERE id= '"+stdid+"'";
            
            rs = stmt.executeQuery(sql);
            
            if (rs.next()) {
                studentName.setText(rs.getString("stdName"));
                fatherName.setText(rs.getString("stdFatherName"));
                cityName.setText(rs.getString("stdCity"));
                blood.setText(rs.getString("stdBloodGroup"));
                phoneNo.setText(rs.getString("stdPhone"));
                stdClass.setText(String.format("%s", rs.getInt("stdClass")));
            }
            else{
                JOptionPane.showMessageDialog(null, "Record Not Found!");
            }
            
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchBTNActionPerformed

    private void studentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDActionPerformed

    private void addStudentBackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentBackBTNActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        home Object = new home();
        Object.setVisible(true);
    }//GEN-LAST:event_addStudentBackBTNActionPerformed

    private void deleteBTNunderSTDUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNunderSTDUpdateActionPerformed
        // TODO add your handling code here:
        try{
            
            stmt = conn.createStatement();
            int stdId = Integer.parseInt(studentID.getText());
            String sql = "DELETE FROM student WHERE id= '"+stdId+"'";
            
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data Is Succesfully Deleted!");
            
            
        }catch(NumberFormatException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_deleteBTNunderSTDUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new studentUpdate().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutBTN;
    private javax.swing.JMenu aboutMenu;
    private javax.swing.JButton addStudentBackBTN;
    private javax.swing.JButton addStudentSubmitBTN;
    private javax.swing.JTextField blood;
    private javax.swing.JTextField cityName;
    private javax.swing.JButton deleteBTNunderSTDUpdate;
    private javax.swing.JTextField fatherName;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem homeBTNunderFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem logoutMenuUnderFile;
    private javax.swing.JTextField phoneNo;
    private javax.swing.JButton searchBTN;
    private javax.swing.JTextField stdClass;
    private javax.swing.JLabel stdID;
    private javax.swing.JTextField studentID;
    private javax.swing.JTextField studentName;
    // End of variables declaration//GEN-END:variables
}
